### ISSUE TITLE
Audit relevant execution info

### ISSUE THREAD

**Issue by rkenmi** [ray-project/deltacat#127]
#### Background

We need the ability to separate data quality issues from other issues such as execution itself. For example, missing manifests when reading, a new delta being appended when compaction is in progress etc. 

#### Solution

To avoid these kind of issues, we want DeltaCAT method `compact_partitions` to be deterministic. This will also help reason about why the compactor behaved certain way in future. 

#### Acceptance Criteria

- We will store history of the states the compacted partition locator went through. 
- We will store total number of manifests we processed and their ranges along with partition locators. 
- We will create a new compaction completion file to store all this for auditability.

**Comment by raghumdani** [comment]
Addressed in #146
