### ISSUE TITLE
Run linter automatically for each commit and PR

### ISSUE THREAD

**Issue by pdames** [ray-project/deltacat#60]
To ensure that styling remains consistent across subsequent PRs, please provide a simple script that can be run to setup Git commit hooks. For example:

https://github.com/ray-project/ray/blob/master/setup_hooks.sh

We should also ensure that our CI workflow runs a linter check on all PRs. For example, here's a similar check that ensures that Apache license header is present in all new files added to a PR:

https://github.com/ray-project/ray_beam_runner/blob/master/.github/workflows/ci.yml#L74-L85

_Originally posted by @pdames in https://github.com/ray-project/deltacat/issues/47#issuecomment-1415109266_

**Comment by pfaraone** [comment]
Closing this issue as it is handled by https://github.com/ray-project/deltacat/pull/47
